### ISSUE TITLE
Question about the supplementary video

### ISSUE THREAD

**Issue by L4zyy** [HKUST-Aerial-Robotics/DSP#2]
Thank you for sharing this amazing work!

I watched your supplementary video and surprised by the good quality. i wonder if you predict trajectories for all objects in one calculation or predict each object as target object then combine the results?

**Comment by MasterIzumi** [comment]
@L4zyy Thanks for your comments. In the supplementary video, we just collect all the target vehicles as a batch. The network generates all trajectories in one forward pass. Essentially, the predictions for each vehicle are independent.
I think there may be some methods to make this process more efficient. For example, we can have multiple goal decoders and trajectory decoders, while the encoder part is shared (similar to LaneGCN).

**Comment by L4zyy** [comment]
> @L4zyy Thanks for your comments. In the supplementary video, we just collect all the target vehicles as a batch. The network generates all trajectories in one forward pass. Essentially, the predictions for each vehicle are independent. I think there may be some methods to make this process more efficient. For example, we can have multiple goal decoders and trajectory decoders, while the encoder part is shared (similar to LaneGCN).

Does "collect all the target vehicles as a batch" means for each target vehicle, you transform all positions to its local coordinates? (If there are 10 vehicles, you will do 10 transformations?)

**Comment by MasterIzumi** [comment]
@L4zyy Exactly, the current model only supports one target vehicle.

**Comment by L4zyy** [comment]
Got it. Thank you again for the quick and detailed replies!
