### ISSUE TITLE
question about data generation

### ISSUE THREAD

**Issue by CHEN-H01** [HKUST-Aerial-Robotics/DSP#4]
![image](https://user-images.githubusercontent.com/73165749/222880368-6b218cbe-cd37-4636-b235-b7d726402d16.png)
![image](https://user-images.githubusercontent.com/73165749/222880457-9b69a110-de02-4a94-b19f-6d8344ed41ed.png)
In line 341, I got a problem called **'MultiPolygon' object is not iterable**, Is it a code problem?

**Comment by MasterIzumi** [comment]
@CHEN-H01 Hi, could you please tell me the version of Shapely you are using? It seems that this method (convert to list) is deprecated in the latest Shapely.

**Comment by CHEN-H01** [comment]
> @CHEN-H01 Hi, could you please tell me the version of Shapely you are using? It seems that this method (convert to list) is deprecated in the latest Shapely.

Hi, thanks for the reply. I use the 2.0.1 version
